// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjJzSkdl9ZtX_peN23TvbIpqm1LbZHOk',
    appId: '1:887078461752:web:a8edc20695602464d761cd',
    messagingSenderId: '887078461752',
    projectId: 'nightingale-chatapp',
    authDomain: 'nightingale-chatapp.firebaseapp.com',
    storageBucket: 'nightingale-chatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxaEQzxK2k-3WC9NmYM3uXsGrJNzleoQ',
    appId: '1:887078461752:android:420ea34e8bd5d9ffd761cd',
    messagingSenderId: '887078461752',
    projectId: 'nightingale-chatapp',
    storageBucket: 'nightingale-chatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHqYp71dgLghTjhDIHpCRm6SSKZOJadkk',
    appId: '1:887078461752:ios:8fada6037343a27bd761cd',
    messagingSenderId: '887078461752',
    projectId: 'nightingale-chatapp',
    storageBucket: 'nightingale-chatapp.appspot.com',
    iosClientId: '887078461752-hcpipkj9h92nb41d3tfcpfn3mt6ue1sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.nightingaleFlutterChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqYp71dgLghTjhDIHpCRm6SSKZOJadkk',
    appId: '1:887078461752:ios:d5955e42c2a5a3e2d761cd',
    messagingSenderId: '887078461752',
    projectId: 'nightingale-chatapp',
    storageBucket: 'nightingale-chatapp.appspot.com',
    iosClientId: '887078461752-2flid40spibg26j6afm0a6mfihjvbb4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.nightingaleFlutterChatapp.RunnerTests',
  );
}
